./gradlew build publishJvmPublicationToSnapshotRepository publishJsPublicationToSnapshotRepository publishKotlinMultiplatformPublicationToSnapshotRepository publishLinuxPublicationToSnapshotRepository publishMetadataPublicationToSnapshotRepository publishLinuxArm64PublicationToSnapshotRepository publishLinuxArm32HfpPublicationToSnapshotRepository || exit 1
exit 0
