./gradlew build -x watchosX64Test publishIosArm64PublicationToSnapshotRepository publishIosX64PublicationToSnapshotRepository \
publishMacosX64PublicationToSnapshotRepository \
publishTvosArm64PublicationToSnapshotRepository publishTvosX64PublicationToSnapshotRepository \
publishWatchosArm32PublicationToSnapshotRepository publishWatchosArm64PublicationToSnapshotRepository \
publishWatchosX64PublicationToSnapshotRepository \
publishMacosArm64PublicationToSnapshotRepository publishIosSimulatorArm64PublicationToSnapshotRepository \
publishTvosSimulatorArm64PublicationToSnapshotRepository publishWatchosSimulatorArm64PublicationToSnapshotRepository -x jsBrowserTest -x wasmJsBrowserTest || exit 1
exit 0
