./gradlew build -x watchosX64Test publishIosArm64PublicationToMavenRepository publishIosX64PublicationToMavenRepository \
publishMacosX64PublicationToMavenRepository publishIosArm32PublicationToMavenRepository \
publishTvosArm64PublicationToMavenRepository publishTvosX64PublicationToMavenRepository \
publishWatchosArm32PublicationToMavenRepository publishWatchosArm64PublicationToMavenRepository \
publishWatchosX86PublicationToMavenRepository publishWatchosX64PublicationToMavenRepository \
publishMacosArm64PublicationToMavenRepository publishIosSimulatorArm64PublicationToMavenRepository \
publishTvosSimulatorArm64PublicationToMavenRepository publishWatchosSimulatorArm64PublicationToMavenRepository
